# Generated by Django 6.0.2 on 2026-02-23 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='price',
            new_name='amount',
        ),
    ]
